//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Qt.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IQtListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class QtBaseListener : IQtListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="QtParser.unit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnit([NotNull] QtParser.UnitContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QtParser.unit"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnit([NotNull] QtParser.UnitContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QtParser.def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDef([NotNull] QtParser.DefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QtParser.def"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDef([NotNull] QtParser.DefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QtParser.ctxExt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCtxExt([NotNull] QtParser.CtxExtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QtParser.ctxExt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCtxExt([NotNull] QtParser.CtxExtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QtParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] QtParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QtParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] QtParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QtParser.letExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLetExpr([NotNull] QtParser.LetExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QtParser.letExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLetExpr([NotNull] QtParser.LetExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QtParser.idExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdExpr([NotNull] QtParser.IdExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QtParser.idExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdExpr([NotNull] QtParser.IdExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QtParser.elimExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElimExpr([NotNull] QtParser.ElimExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QtParser.elimExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElimExpr([NotNull] QtParser.ElimExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="QtParser.elimCase"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElimCase([NotNull] QtParser.ElimCaseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="QtParser.elimCase"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElimCase([NotNull] QtParser.ElimCaseContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
