//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Qt.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="QtParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IQtListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="QtParser.unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnit([NotNull] QtParser.UnitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QtParser.unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnit([NotNull] QtParser.UnitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QtParser.def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDef([NotNull] QtParser.DefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QtParser.def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDef([NotNull] QtParser.DefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QtParser.ctxExt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCtxExt([NotNull] QtParser.CtxExtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QtParser.ctxExt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCtxExt([NotNull] QtParser.CtxExtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QtParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] QtParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QtParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] QtParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QtParser.argExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgExpr([NotNull] QtParser.ArgExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QtParser.argExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgExpr([NotNull] QtParser.ArgExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QtParser.letExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLetExpr([NotNull] QtParser.LetExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QtParser.letExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLetExpr([NotNull] QtParser.LetExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QtParser.idExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdExpr([NotNull] QtParser.IdExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QtParser.idExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdExpr([NotNull] QtParser.IdExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QtParser.elimExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElimExpr([NotNull] QtParser.ElimExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QtParser.elimExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElimExpr([NotNull] QtParser.ElimExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="QtParser.elimCase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElimCase([NotNull] QtParser.ElimCaseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="QtParser.elimCase"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElimCase([NotNull] QtParser.ElimCaseContext context);
}
