//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Qt.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class QtParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, ID=15, NUM=16, WS=17;
	public const int
		RULE_unit = 0, RULE_def = 1, RULE_ctxExt = 2, RULE_expr = 3, RULE_argExpr = 4, 
		RULE_letExpr = 5, RULE_idExpr = 6, RULE_elimExpr = 7, RULE_elimCase = 8;
	public static readonly string[] ruleNames = {
		"unit", "def", "ctxExt", "expr", "argExpr", "letExpr", "idExpr", "elimExpr", 
		"elimCase"
	};

	private static readonly string[] _LiteralNames = {
		null, "'def'", "':'", "':='", "'.'", "'('", "')'", "'+'", "'='", "'let'", 
		"'in'", "'elim'", "'into'", "'|'", "'=>'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, "ID", "NUM", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Qt.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static QtParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public QtParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public QtParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class UnitContext : ParserRuleContext {
		public DefContext _def;
		public IList<DefContext> _defs = new List<DefContext>();
		public DefContext[] def() {
			return GetRuleContexts<DefContext>();
		}
		public DefContext def(int i) {
			return GetRuleContext<DefContext>(i);
		}
		public UnitContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_unit; } }
		public override void EnterRule(IParseTreeListener listener) {
			IQtListener typedListener = listener as IQtListener;
			if (typedListener != null) typedListener.EnterUnit(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IQtListener typedListener = listener as IQtListener;
			if (typedListener != null) typedListener.ExitUnit(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQtVisitor<TResult> typedVisitor = visitor as IQtVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitUnit(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public UnitContext unit() {
		UnitContext _localctx = new UnitContext(Context, State);
		EnterRule(_localctx, 0, RULE_unit);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 21;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__0) {
				{
				{
				State = 18; _localctx._def = def();
				_localctx._defs.Add(_localctx._def);
				}
				}
				State = 23;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DefContext : ParserRuleContext {
		public IToken name;
		public CtxExtContext _ctxExt;
		public IList<CtxExtContext> _exts = new List<CtxExtContext>();
		public ExprContext retTy;
		public ExprContext body;
		public ITerminalNode ID() { return GetToken(QtParser.ID, 0); }
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public CtxExtContext[] ctxExt() {
			return GetRuleContexts<CtxExtContext>();
		}
		public CtxExtContext ctxExt(int i) {
			return GetRuleContext<CtxExtContext>(i);
		}
		public DefContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_def; } }
		public override void EnterRule(IParseTreeListener listener) {
			IQtListener typedListener = listener as IQtListener;
			if (typedListener != null) typedListener.EnterDef(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IQtListener typedListener = listener as IQtListener;
			if (typedListener != null) typedListener.ExitDef(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQtVisitor<TResult> typedVisitor = visitor as IQtVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDef(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DefContext def() {
		DefContext _localctx = new DefContext(Context, State);
		EnterRule(_localctx, 2, RULE_def);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 24; Match(T__0);
			State = 25; _localctx.name = Match(ID);
			State = 29;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__4) {
				{
				{
				State = 26; _localctx._ctxExt = ctxExt();
				_localctx._exts.Add(_localctx._ctxExt);
				}
				}
				State = 31;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 32; Match(T__1);
			State = 33; _localctx.retTy = expr(0);
			State = 34; Match(T__2);
			State = 35; _localctx.body = expr(0);
			State = 36; Match(T__3);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CtxExtContext : ParserRuleContext {
		public IToken _ID;
		public IList<IToken> _names = new List<IToken>();
		public ExprContext ty;
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode[] ID() { return GetTokens(QtParser.ID); }
		public ITerminalNode ID(int i) {
			return GetToken(QtParser.ID, i);
		}
		public CtxExtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_ctxExt; } }
		public override void EnterRule(IParseTreeListener listener) {
			IQtListener typedListener = listener as IQtListener;
			if (typedListener != null) typedListener.EnterCtxExt(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IQtListener typedListener = listener as IQtListener;
			if (typedListener != null) typedListener.ExitCtxExt(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQtVisitor<TResult> typedVisitor = visitor as IQtVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCtxExt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CtxExtContext ctxExt() {
		CtxExtContext _localctx = new CtxExtContext(Context, State);
		EnterRule(_localctx, 4, RULE_ctxExt);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 38; Match(T__4);
			State = 40;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 39; _localctx._ID = Match(ID);
				_localctx._names.Add(_localctx._ID);
				}
				}
				State = 42;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==ID );
			State = 44; Match(T__1);
			State = 45; _localctx.ty = expr(0);
			State = 46; Match(T__5);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		public ExprContext left;
		public ExprContext parenthesized;
		public IToken fun;
		public ArgExprContext _argExpr;
		public IList<ArgExprContext> _args = new List<ArgExprContext>();
		public LetExprContext let;
		public ElimExprContext elim;
		public IToken num;
		public IdExprContext id;
		public IToken op;
		public ExprContext right;
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public ITerminalNode ID() { return GetToken(QtParser.ID, 0); }
		public ArgExprContext[] argExpr() {
			return GetRuleContexts<ArgExprContext>();
		}
		public ArgExprContext argExpr(int i) {
			return GetRuleContext<ArgExprContext>(i);
		}
		public LetExprContext letExpr() {
			return GetRuleContext<LetExprContext>(0);
		}
		public ElimExprContext elimExpr() {
			return GetRuleContext<ElimExprContext>(0);
		}
		public ITerminalNode NUM() { return GetToken(QtParser.NUM, 0); }
		public IdExprContext idExpr() {
			return GetRuleContext<IdExprContext>(0);
		}
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
		public override void EnterRule(IParseTreeListener listener) {
			IQtListener typedListener = listener as IQtListener;
			if (typedListener != null) typedListener.EnterExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IQtListener typedListener = listener as IQtListener;
			if (typedListener != null) typedListener.ExitExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQtVisitor<TResult> typedVisitor = visitor as IQtVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		return expr(0);
	}

	private ExprContext expr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExprContext _localctx = new ExprContext(Context, _parentState);
		ExprContext _prevctx = _localctx;
		int _startState = 6;
		EnterRecursionRule(_localctx, 6, RULE_expr, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 63;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
			case 1:
				{
				State = 49; Match(T__4);
				State = 50; _localctx.parenthesized = expr(0);
				State = 51; Match(T__5);
				}
				break;
			case 2:
				{
				State = 53; _localctx.fun = Match(ID);
				State = 55;
				ErrorHandler.Sync(this);
				_alt = 1;
				do {
					switch (_alt) {
					case 1:
						{
						{
						State = 54; _localctx._argExpr = argExpr();
						_localctx._args.Add(_localctx._argExpr);
						}
						}
						break;
					default:
						throw new NoViableAltException(this);
					}
					State = 57;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,3,Context);
				} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
				}
				break;
			case 3:
				{
				State = 59; _localctx.let = letExpr();
				}
				break;
			case 4:
				{
				State = 60; _localctx.elim = elimExpr();
				}
				break;
			case 5:
				{
				State = 61; _localctx.num = Match(NUM);
				}
				break;
			case 6:
				{
				State = 62; _localctx.id = idExpr();
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 70;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,5,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new ExprContext(_parentctx, _parentState);
					_localctx.left = _prevctx;
					PushNewRecursionContext(_localctx, _startState, RULE_expr);
					State = 65;
					if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
					State = 66;
					_localctx.op = TokenStream.LT(1);
					_la = TokenStream.LA(1);
					if ( !(_la==T__6 || _la==T__7) ) {
						_localctx.op = ErrorHandler.RecoverInline(this);
					}
					else {
						ErrorHandler.ReportMatch(this);
					    Consume();
					}
					State = 67; _localctx.right = expr(4);
					}
					} 
				}
				State = 72;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,5,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class ArgExprContext : ParserRuleContext {
		public ExprContext parenthesized;
		public IToken num;
		public IdExprContext id;
		public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ITerminalNode NUM() { return GetToken(QtParser.NUM, 0); }
		public IdExprContext idExpr() {
			return GetRuleContext<IdExprContext>(0);
		}
		public ArgExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_argExpr; } }
		public override void EnterRule(IParseTreeListener listener) {
			IQtListener typedListener = listener as IQtListener;
			if (typedListener != null) typedListener.EnterArgExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IQtListener typedListener = listener as IQtListener;
			if (typedListener != null) typedListener.ExitArgExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQtVisitor<TResult> typedVisitor = visitor as IQtVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArgExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArgExprContext argExpr() {
		ArgExprContext _localctx = new ArgExprContext(Context, State);
		EnterRule(_localctx, 8, RULE_argExpr);
		try {
			State = 79;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__4:
				EnterOuterAlt(_localctx, 1);
				{
				State = 73; Match(T__4);
				State = 74; _localctx.parenthesized = expr(0);
				State = 75; Match(T__5);
				}
				break;
			case NUM:
				EnterOuterAlt(_localctx, 2);
				{
				State = 77; _localctx.num = Match(NUM);
				}
				break;
			case ID:
				EnterOuterAlt(_localctx, 3);
				{
				State = 78; _localctx.id = idExpr();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LetExprContext : ParserRuleContext {
		public IToken varName;
		public ExprContext ty;
		public ExprContext val;
		public ExprContext body;
		public ITerminalNode ID() { return GetToken(QtParser.ID, 0); }
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public LetExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_letExpr; } }
		public override void EnterRule(IParseTreeListener listener) {
			IQtListener typedListener = listener as IQtListener;
			if (typedListener != null) typedListener.EnterLetExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IQtListener typedListener = listener as IQtListener;
			if (typedListener != null) typedListener.ExitLetExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQtVisitor<TResult> typedVisitor = visitor as IQtVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLetExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LetExprContext letExpr() {
		LetExprContext _localctx = new LetExprContext(Context, State);
		EnterRule(_localctx, 10, RULE_letExpr);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 81; Match(T__8);
			State = 82; _localctx.varName = Match(ID);
			State = 83; Match(T__1);
			State = 84; _localctx.ty = expr(0);
			State = 85; Match(T__2);
			State = 86; _localctx.val = expr(0);
			State = 87; Match(T__9);
			State = 88; _localctx.body = expr(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IdExprContext : ParserRuleContext {
		public IToken id;
		public ITerminalNode ID() { return GetToken(QtParser.ID, 0); }
		public IdExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_idExpr; } }
		public override void EnterRule(IParseTreeListener listener) {
			IQtListener typedListener = listener as IQtListener;
			if (typedListener != null) typedListener.EnterIdExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IQtListener typedListener = listener as IQtListener;
			if (typedListener != null) typedListener.ExitIdExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQtVisitor<TResult> typedVisitor = visitor as IQtVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIdExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IdExprContext idExpr() {
		IdExprContext _localctx = new IdExprContext(Context, State);
		EnterRule(_localctx, 12, RULE_idExpr);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 90; _localctx.id = Match(ID);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ElimExprContext : ParserRuleContext {
		public ExprContext discriminee;
		public CtxExtContext _ctxExt;
		public IList<CtxExtContext> _exts = new List<CtxExtContext>();
		public ExprContext intoTy;
		public ElimCaseContext _elimCase;
		public IList<ElimCaseContext> _cases = new List<ElimCaseContext>();
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public CtxExtContext[] ctxExt() {
			return GetRuleContexts<CtxExtContext>();
		}
		public CtxExtContext ctxExt(int i) {
			return GetRuleContext<CtxExtContext>(i);
		}
		public ElimCaseContext[] elimCase() {
			return GetRuleContexts<ElimCaseContext>();
		}
		public ElimCaseContext elimCase(int i) {
			return GetRuleContext<ElimCaseContext>(i);
		}
		public ElimExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_elimExpr; } }
		public override void EnterRule(IParseTreeListener listener) {
			IQtListener typedListener = listener as IQtListener;
			if (typedListener != null) typedListener.EnterElimExpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IQtListener typedListener = listener as IQtListener;
			if (typedListener != null) typedListener.ExitElimExpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQtVisitor<TResult> typedVisitor = visitor as IQtVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitElimExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ElimExprContext elimExpr() {
		ElimExprContext _localctx = new ElimExprContext(Context, State);
		EnterRule(_localctx, 14, RULE_elimExpr);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 92; Match(T__10);
			State = 93; _localctx.discriminee = expr(0);
			State = 94; Match(T__11);
			State = 98;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__4) {
				{
				{
				State = 95; _localctx._ctxExt = ctxExt();
				_localctx._exts.Add(_localctx._ctxExt);
				}
				}
				State = 100;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 101; Match(T__1);
			State = 102; _localctx.intoTy = expr(0);
			State = 106;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,8,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 103; _localctx._elimCase = elimCase();
					_localctx._cases.Add(_localctx._elimCase);
					}
					} 
				}
				State = 108;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,8,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ElimCaseContext : ParserRuleContext {
		public CtxExtContext _ctxExt;
		public IList<CtxExtContext> _exts = new List<CtxExtContext>();
		public ExprContext caseTy;
		public ExprContext body;
		public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public CtxExtContext[] ctxExt() {
			return GetRuleContexts<CtxExtContext>();
		}
		public CtxExtContext ctxExt(int i) {
			return GetRuleContext<CtxExtContext>(i);
		}
		public ElimCaseContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_elimCase; } }
		public override void EnterRule(IParseTreeListener listener) {
			IQtListener typedListener = listener as IQtListener;
			if (typedListener != null) typedListener.EnterElimCase(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			IQtListener typedListener = listener as IQtListener;
			if (typedListener != null) typedListener.ExitElimCase(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IQtVisitor<TResult> typedVisitor = visitor as IQtVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitElimCase(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ElimCaseContext elimCase() {
		ElimCaseContext _localctx = new ElimCaseContext(Context, State);
		EnterRule(_localctx, 16, RULE_elimCase);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 109; Match(T__12);
			State = 113;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__4) {
				{
				{
				State = 110; _localctx._ctxExt = ctxExt();
				_localctx._exts.Add(_localctx._ctxExt);
				}
				}
				State = 115;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 116; Match(T__1);
			State = 117; _localctx.caseTy = expr(0);
			State = 118; Match(T__13);
			State = 119; _localctx.body = expr(0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 3: return expr_sempred((ExprContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expr_sempred(ExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 3);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\x13', '|', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x3', '\x2', '\a', 
		'\x2', '\x16', '\n', '\x2', '\f', '\x2', '\xE', '\x2', '\x19', '\v', '\x2', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\a', '\x3', '\x1E', '\n', '\x3', 
		'\f', '\x3', '\xE', '\x3', '!', '\v', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', 
		'\x3', '\x4', '\x6', '\x4', '+', '\n', '\x4', '\r', '\x4', '\xE', '\x4', 
		',', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x5', '\x6', '\x5', ':', '\n', '\x5', '\r', '\x5', '\xE', '\x5', 
		';', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x5', '\x5', 
		'\x42', '\n', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\a', '\x5', 
		'G', '\n', '\x5', '\f', '\x5', '\xE', '\x5', 'J', '\v', '\x5', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x5', '\x6', 'R', '\n', '\x6', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\a', '\t', '\x63', '\n', '\t', '\f', '\t', '\xE', 
		'\t', '\x66', '\v', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\a', 
		'\t', 'k', '\n', '\t', '\f', '\t', '\xE', '\t', 'n', '\v', '\t', '\x3', 
		'\n', '\x3', '\n', '\a', '\n', 'r', '\n', '\n', '\f', '\n', '\xE', '\n', 
		'u', '\v', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x2', '\x3', '\b', '\v', '\x2', '\x4', '\x6', '\b', 
		'\n', '\f', '\xE', '\x10', '\x12', '\x2', '\x3', '\x3', '\x2', '\t', '\n', 
		'\x2', '\x81', '\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x4', '\x1A', 
		'\x3', '\x2', '\x2', '\x2', '\x6', '(', '\x3', '\x2', '\x2', '\x2', '\b', 
		'\x41', '\x3', '\x2', '\x2', '\x2', '\n', 'Q', '\x3', '\x2', '\x2', '\x2', 
		'\f', 'S', '\x3', '\x2', '\x2', '\x2', '\xE', '\\', '\x3', '\x2', '\x2', 
		'\x2', '\x10', '^', '\x3', '\x2', '\x2', '\x2', '\x12', 'o', '\x3', '\x2', 
		'\x2', '\x2', '\x14', '\x16', '\x5', '\x4', '\x3', '\x2', '\x15', '\x14', 
		'\x3', '\x2', '\x2', '\x2', '\x16', '\x19', '\x3', '\x2', '\x2', '\x2', 
		'\x17', '\x15', '\x3', '\x2', '\x2', '\x2', '\x17', '\x18', '\x3', '\x2', 
		'\x2', '\x2', '\x18', '\x3', '\x3', '\x2', '\x2', '\x2', '\x19', '\x17', 
		'\x3', '\x2', '\x2', '\x2', '\x1A', '\x1B', '\a', '\x3', '\x2', '\x2', 
		'\x1B', '\x1F', '\a', '\x11', '\x2', '\x2', '\x1C', '\x1E', '\x5', '\x6', 
		'\x4', '\x2', '\x1D', '\x1C', '\x3', '\x2', '\x2', '\x2', '\x1E', '!', 
		'\x3', '\x2', '\x2', '\x2', '\x1F', '\x1D', '\x3', '\x2', '\x2', '\x2', 
		'\x1F', ' ', '\x3', '\x2', '\x2', '\x2', ' ', '\"', '\x3', '\x2', '\x2', 
		'\x2', '!', '\x1F', '\x3', '\x2', '\x2', '\x2', '\"', '#', '\a', '\x4', 
		'\x2', '\x2', '#', '$', '\x5', '\b', '\x5', '\x2', '$', '%', '\a', '\x5', 
		'\x2', '\x2', '%', '&', '\x5', '\b', '\x5', '\x2', '&', '\'', '\a', '\x6', 
		'\x2', '\x2', '\'', '\x5', '\x3', '\x2', '\x2', '\x2', '(', '*', '\a', 
		'\a', '\x2', '\x2', ')', '+', '\a', '\x11', '\x2', '\x2', '*', ')', '\x3', 
		'\x2', '\x2', '\x2', '+', ',', '\x3', '\x2', '\x2', '\x2', ',', '*', '\x3', 
		'\x2', '\x2', '\x2', ',', '-', '\x3', '\x2', '\x2', '\x2', '-', '.', '\x3', 
		'\x2', '\x2', '\x2', '.', '/', '\a', '\x4', '\x2', '\x2', '/', '\x30', 
		'\x5', '\b', '\x5', '\x2', '\x30', '\x31', '\a', '\b', '\x2', '\x2', '\x31', 
		'\a', '\x3', '\x2', '\x2', '\x2', '\x32', '\x33', '\b', '\x5', '\x1', 
		'\x2', '\x33', '\x34', '\a', '\a', '\x2', '\x2', '\x34', '\x35', '\x5', 
		'\b', '\x5', '\x2', '\x35', '\x36', '\a', '\b', '\x2', '\x2', '\x36', 
		'\x42', '\x3', '\x2', '\x2', '\x2', '\x37', '\x39', '\a', '\x11', '\x2', 
		'\x2', '\x38', ':', '\x5', '\n', '\x6', '\x2', '\x39', '\x38', '\x3', 
		'\x2', '\x2', '\x2', ':', ';', '\x3', '\x2', '\x2', '\x2', ';', '\x39', 
		'\x3', '\x2', '\x2', '\x2', ';', '<', '\x3', '\x2', '\x2', '\x2', '<', 
		'\x42', '\x3', '\x2', '\x2', '\x2', '=', '\x42', '\x5', '\f', '\a', '\x2', 
		'>', '\x42', '\x5', '\x10', '\t', '\x2', '?', '\x42', '\a', '\x12', '\x2', 
		'\x2', '@', '\x42', '\x5', '\xE', '\b', '\x2', '\x41', '\x32', '\x3', 
		'\x2', '\x2', '\x2', '\x41', '\x37', '\x3', '\x2', '\x2', '\x2', '\x41', 
		'=', '\x3', '\x2', '\x2', '\x2', '\x41', '>', '\x3', '\x2', '\x2', '\x2', 
		'\x41', '?', '\x3', '\x2', '\x2', '\x2', '\x41', '@', '\x3', '\x2', '\x2', 
		'\x2', '\x42', 'H', '\x3', '\x2', '\x2', '\x2', '\x43', '\x44', '\f', 
		'\x5', '\x2', '\x2', '\x44', '\x45', '\t', '\x2', '\x2', '\x2', '\x45', 
		'G', '\x5', '\b', '\x5', '\x6', '\x46', '\x43', '\x3', '\x2', '\x2', '\x2', 
		'G', 'J', '\x3', '\x2', '\x2', '\x2', 'H', '\x46', '\x3', '\x2', '\x2', 
		'\x2', 'H', 'I', '\x3', '\x2', '\x2', '\x2', 'I', '\t', '\x3', '\x2', 
		'\x2', '\x2', 'J', 'H', '\x3', '\x2', '\x2', '\x2', 'K', 'L', '\a', '\a', 
		'\x2', '\x2', 'L', 'M', '\x5', '\b', '\x5', '\x2', 'M', 'N', '\a', '\b', 
		'\x2', '\x2', 'N', 'R', '\x3', '\x2', '\x2', '\x2', 'O', 'R', '\a', '\x12', 
		'\x2', '\x2', 'P', 'R', '\x5', '\xE', '\b', '\x2', 'Q', 'K', '\x3', '\x2', 
		'\x2', '\x2', 'Q', 'O', '\x3', '\x2', '\x2', '\x2', 'Q', 'P', '\x3', '\x2', 
		'\x2', '\x2', 'R', '\v', '\x3', '\x2', '\x2', '\x2', 'S', 'T', '\a', '\v', 
		'\x2', '\x2', 'T', 'U', '\a', '\x11', '\x2', '\x2', 'U', 'V', '\a', '\x4', 
		'\x2', '\x2', 'V', 'W', '\x5', '\b', '\x5', '\x2', 'W', 'X', '\a', '\x5', 
		'\x2', '\x2', 'X', 'Y', '\x5', '\b', '\x5', '\x2', 'Y', 'Z', '\a', '\f', 
		'\x2', '\x2', 'Z', '[', '\x5', '\b', '\x5', '\x2', '[', '\r', '\x3', '\x2', 
		'\x2', '\x2', '\\', ']', '\a', '\x11', '\x2', '\x2', ']', '\xF', '\x3', 
		'\x2', '\x2', '\x2', '^', '_', '\a', '\r', '\x2', '\x2', '_', '`', '\x5', 
		'\b', '\x5', '\x2', '`', '\x64', '\a', '\xE', '\x2', '\x2', '\x61', '\x63', 
		'\x5', '\x6', '\x4', '\x2', '\x62', '\x61', '\x3', '\x2', '\x2', '\x2', 
		'\x63', '\x66', '\x3', '\x2', '\x2', '\x2', '\x64', '\x62', '\x3', '\x2', 
		'\x2', '\x2', '\x64', '\x65', '\x3', '\x2', '\x2', '\x2', '\x65', 'g', 
		'\x3', '\x2', '\x2', '\x2', '\x66', '\x64', '\x3', '\x2', '\x2', '\x2', 
		'g', 'h', '\a', '\x4', '\x2', '\x2', 'h', 'l', '\x5', '\b', '\x5', '\x2', 
		'i', 'k', '\x5', '\x12', '\n', '\x2', 'j', 'i', '\x3', '\x2', '\x2', '\x2', 
		'k', 'n', '\x3', '\x2', '\x2', '\x2', 'l', 'j', '\x3', '\x2', '\x2', '\x2', 
		'l', 'm', '\x3', '\x2', '\x2', '\x2', 'm', '\x11', '\x3', '\x2', '\x2', 
		'\x2', 'n', 'l', '\x3', '\x2', '\x2', '\x2', 'o', 's', '\a', '\xF', '\x2', 
		'\x2', 'p', 'r', '\x5', '\x6', '\x4', '\x2', 'q', 'p', '\x3', '\x2', '\x2', 
		'\x2', 'r', 'u', '\x3', '\x2', '\x2', '\x2', 's', 'q', '\x3', '\x2', '\x2', 
		'\x2', 's', 't', '\x3', '\x2', '\x2', '\x2', 't', 'v', '\x3', '\x2', '\x2', 
		'\x2', 'u', 's', '\x3', '\x2', '\x2', '\x2', 'v', 'w', '\a', '\x4', '\x2', 
		'\x2', 'w', 'x', '\x5', '\b', '\x5', '\x2', 'x', 'y', '\a', '\x10', '\x2', 
		'\x2', 'y', 'z', '\x5', '\b', '\x5', '\x2', 'z', '\x13', '\x3', '\x2', 
		'\x2', '\x2', '\f', '\x17', '\x1F', ',', ';', '\x41', 'H', 'Q', '\x64', 
		'l', 's',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
