[package]
name = "eqlog-test-compile"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eqlog = { path = "../eqlog", features = ["rebuild"] }
indoc = ">= 0"
tempdir = ">= 0"
log = ">= 0"
test-log = ">= 0"
env_logger = ">= 0"
