#!/bin/sh
#
# Examples:
# > ./run-docker bash
#
# > export RUSTFLAGS="-A dead_code -A unused_variables -A unused_imports -A dead_code -A unused_variables -A unused_imports"
# > ./run-docker cargo build

repo_root="$(git rev-parse --show-toplevel)"

docker run \
	--interactive \
	--tty \
	--user $(id --user):$(id --group) \
	--volume "$repo_root":"$repo_root" \
	--workdir "$(pwd)" \
	--env "RUSTFLAGS=$RUSTFLAGS" \
	--env "RUST_BACKTRACE=$RUST_BACKTRACE" \
	--env "CARGO_HOME=$repo_root/.cargo" \
	rust:1.58 \
	$@
